services:
  web:
    build: .
    image: dannyben/redirector
    ports: ["3000:3000"]
    volumes: ['./config.ru:/app/config.ru']
    environment:
      REDIRECT1: .*\.local==!https://www.google.com
      REDIRECT2: .*\.lvh\.me==https://github.com
